services:
  - type: web
    name: playwright-app
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y \
        libgtk-4-1 \
        libgraphene-1.0-0 \
        libgstreamer-gl1.0-0 \
        gstreamer1.0-plugins-bad \
        libavif15 \
        libenchant-2-2 \
        libsecret-1-0 \
        libmanette-0.2-0 \
        libgles2 \
        fonts-liberation \
        libxss1 \
        xdg-utils \
        && pip install -r requirements.txt \
        && playwright install chrome
    startCommand: python your_script.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
